export const strings = {
  brand: {
    name: "Farmacia Atenas",
    word1: "Farmacia",
    word2: "Atenas",
  },

  common: {
    loading: "Cargando...",
    error: "Algo salió mal. Por favor intenta de nuevo.",
    errorTitle: "Algo salió mal",
    empty: "No hay resultados.",
    retry: "Reintentar",
    goCatalog: "Ir al catálogo",
    notFound: {
      title: "Página no encontrada",
      message: "La página que buscas no existe o fue movida.",
    },
    cancel: "Cancelar",
    confirm: "Confirmar",
    save: "Guardar",
    delete: "Eliminar",
    edit: "Editar",
    back: "Volver",
    search: "Buscar",
    close: "Cerrar",
  },

  pwa: {
    install: "Instalar app",
    installAria: "Instalar la aplicación en tu dispositivo",
  },

  validation: {
    required: "Este campo es obligatorio.",
    invalidEmail: "Correo electrónico inválido.",
    invalidPhone: "Número de teléfono inválido.",
    minLength: (n: number) => `Mínimo ${n} caracteres.`,
    maxLength: (n: number) => `Máximo ${n} caracteres.`,
  },

  auth: {
    greeting: "Hola,",
    signIn: "Iniciar sesión",
    signOut: "Cerrar sesión",
    signUp: "Registrarse",
    email: "Correo electrónico",
    password: "Contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    invalidCredentials: "Credenciales inválidas.",
  },

  cart: {
    title: "Carrito",
    empty: "Tu carrito está vacío.",
    emptyHint: "Agrega productos desde el catálogo.",
    goCatalog: "Ver catálogo",
    addItem: "Agregar al carrito",
    removeItem: "Eliminar del carrito",
    checkout: "Proceder al pago",
    total: "Total",
    quantity: "Cantidad",
  },

  products: {
    title: "Productos",
    empty: "No se encontraron productos.",
    outOfStock: "Sin stock",
    addToCart: "Agregar",
    prescription: "Requiere receta médica",
    price: "Precio",
    frequentlyBought: "Comprados frecuentemente",
    emptyHint: "Intenta con otro término o categoría.",
    detail: {
      dialogLabel: "Detalle del producto",
      quantity: "Cantidad",
      available: "Disponible",
      unavailable: "Agotado",
      added: "Agregado al carrito",
      expires: "Vence",
      related: "Productos relacionados",
      notFoundTitle: "Producto no encontrado",
      notFoundMessage:
        "Este producto ya no está disponible en Farmacia Atenas. Explora el resto del catálogo.",
    },
  },

  orders: {
    title: "Mis pedidos",
    empty: "No tienes pedidos aún.",
    create: {
      invalid: "Los datos del pedido no son válidos.",
      notIdentified: "Debes identificarte antes de realizar un pedido.",
      productUnavailable: "Uno de los productos ya no está disponible.",
      insufficientStock: "No hay stock suficiente para uno de los productos.",
      failed: "No se pudo crear el pedido. Intenta de nuevo.",
    },
    receipt: {
      showAtCounter: "Muestra esto en el mostrador",
      orderCode: "Código del pedido",
      qrAlt: "Código QR del pedido",
      summary: "Resumen del pedido",
      total: "Total",
      backToCatalog: "Volver al catálogo",
      notFoundTitle: "Pedido no encontrado",
      notFoundMessage: "El pedido que buscas no existe o el código no es válido.",
    },
    status: {
      pending: "Pendiente",
      processing: "En proceso",
      shipped: "Enviado",
      delivered: "Entregado",
      cancelled: "Cancelado",
    },
    // Maps OrderStatus enum values to their Spanish label.
    statusLabel: {
      PENDIENTE: "Pendiente",
      PROCESANDO: "En proceso",
      COMPLETADA: "Completada",
      CANCELADA: "Cancelada",
    },
    // Maps DeliveryMethod enum values to their Spanish label.
    deliveryLabel: {
      RETIRO_TIENDA: "Retiro en tienda",
      ENVIO_DOMICILIO: "Envío a domicilio",
    },
    // Maps PaymentMethod enum values to their Spanish label.
    paymentMethodLabel: {
      EFECTIVO: "Efectivo",
      TARJETA: "Tarjeta",
      TRANSFERENCIA: "Transferencia",
      PAGO_MOVIL: "Pago móvil",
    },
    // Maps PaymentStatus enum values to their Spanish label.
    paymentStatusLabel: {
      PENDIENTE: "Pago pendiente",
      PAGADO: "Pagado",
    },
  },

  checkout: {
    title: "Finalizar pedido",
    subtitle: "Confirma cómo quieres recibir y pagar tu pedido.",
    deliverySection: "Método de entrega",
    deliveryRetiro: "Retiro en tienda",
    deliveryEnvio: "Envío a domicilio",
    addressSection: "Dirección de envío",
    savedAddresses: "Direcciones guardadas",
    newAddress: "Usar otra dirección",
    address: "Dirección",
    addressPlaceholder: "Calle, edificio, apartamento…",
    city: "Ciudad",
    state: "Estado",
    zipCode: "Código postal",
    zipOptional: "Opcional",
    saveAddress: "Guardar esta dirección para futuros pedidos",
    paymentSection: "Método de pago",
    notesSection: "Notas para el pedido",
    notesPlaceholder: "Instrucciones adicionales (opcional)",
    summary: "Resumen",
    total: "Total",
    submit: "Confirmar pedido",
    submitting: "Procesando…",
    emptyCart: "Tu carrito está vacío.",
    backToCart: "Volver al carrito",
  },

  operator: {
    title: "Operador",
    subtitle: "Recupera un pedido por su código.",
    codeLabel: "Código del pedido",
    codePlaceholder: "FARM-XXXXX",
    searchButton: "Buscar",
    scanButton: "Escanear QR",
    scanTitle: "Escanear código QR",
    scanInstruction: "Apunta la cámara al QR del pedido.",
    scanUnsupported: "Este navegador no permite escanear. Teclea el código manualmente.",
    scanPermissionDenied: "Sin acceso a la cámara. Habilita el permiso o teclea el código.",
    scanError: "No se pudo iniciar la cámara. Intenta de nuevo.",
    emptyTitle: "Busca un pedido",
    emptyMessage: "Escanea el QR del cliente o teclea el código para ver el pedido.",
    notFoundTitle: "Pedido no encontrado",
    notFound: "No existe ningún pedido con ese código.",
    rateLimitedTitle: "Demasiadas búsquedas",
    rateLimitedMessage: "Espera unos segundos antes de volver a buscar.",
    customer: "Cliente",
    phone: "Teléfono",
    email: "Correo",
    items: "Productos",
    total: "Total",
    status: "Estado",
    complete: "Marcar como completada",
    completeError: "No se pudo actualizar el pedido. Intenta de nuevo.",
    alreadyCompleted: "Este pedido ya fue completado.",
    delivery: "Entrega",
    shipping: "Dirección de envío",
    notes: "Notas del cliente",
    payment: {
      section: "Pago",
      method: "Método",
      status: "Estado del pago",
      markPaid: "Marcar como pagado",
      error: "No se pudo actualizar el pago. Intenta de nuevo.",
    },
    manageProducts: "Gestionar productos",
    manageCategories: "Gestionar categorías",
    viewOrders: "Ver pedidos",
    orders: {
      title: "Pedidos",
      subtitle: "Consulta y gestiona los pedidos de la farmacia.",
      searchPlaceholder: "Buscar por código",
      filterAll: "Todos",
      empty: "No hay pedidos",
      emptyHint: "No se encontraron pedidos con estos filtros.",
      itemsCount: (n: number) => `${n} ${n === 1 ? "producto" : "productos"}`,
      pageInfo: (current: number, total: number) => `Página ${current} de ${total}`,
      prev: "Anterior",
      next: "Siguiente",
      backToList: "Volver a pedidos",
      detailTitle: "Detalle del pedido",
      markProcessing: "Marcar en proceso",
      markCancelled: "Cancelar pedido",
      updateError: "No se pudo actualizar el estado. Intenta de nuevo.",
      cancelledNote: "Este pedido fue cancelado.",
    },
  },

  management: {
    title: "Gestión de productos",
    subtitle: "Crea, edita o desactiva productos del catálogo.",
    forbidden: "No tienes permiso para administrar el catálogo.",
    new: "Nuevo producto",
    edit: "Editar",
    delete: "Eliminar",
    empty: "Aún no hay productos.",
    emptyHint: "Crea el primero con “Nuevo producto”.",
    active: "Activo",
    inactive: "Inactivo",
    backToList: "Volver a la lista",
    form: {
      newTitle: "Nuevo producto",
      editTitle: "Editar producto",
      name: "Nombre",
      description: "Descripción",
      price: "Precio",
      category: "Categoría",
      categoryPlaceholder: "Selecciona una categoría",
      expirationDate: "Fecha de vencimiento",
      stock: "Stock",
      imageUrl: "URL de imagen",
      imageUrlHint: "Opcional. Pega un enlace a la imagen del producto.",
      requiresPrescription: "Requiere receta médica",
      save: "Guardar",
      saving: "Guardando…",
      cancel: "Cancelar",
      saveError: "No se pudo guardar el producto. Intenta de nuevo.",
    },
    remove: {
      title: "Eliminar producto",
      message: (name: string) =>
        `Esto quitará “${name}” del catálogo. Si tiene pedidos asociados, se desactivará para preservar el historial.`,
      confirm: "Eliminar",
      cancel: "Cancelar",
      error: "No se pudo eliminar el producto. Intenta de nuevo.",
    },
    categories: {
      title: "Gestión de categorías",
      subtitle: "Crea, edita o elimina las categorías del catálogo.",
      manage: "Gestionar categorías",
      new: "Nueva categoría",
      edit: "Editar",
      delete: "Eliminar",
      empty: "Aún no hay categorías.",
      emptyHint: "Crea la primera con “Nueva categoría”.",
      productCount: (n: number) => `${n} ${n === 1 ? "producto" : "productos"}`,
      forbidden: "No tienes permiso para administrar categorías.",
      form: {
        newTitle: "Nueva categoría",
        editTitle: "Editar categoría",
        name: "Nombre",
        save: "Guardar",
        saving: "Guardando…",
        cancel: "Cancelar",
        duplicate: "Ya existe una categoría con ese nombre.",
        saveError: "No se pudo guardar la categoría. Intenta de nuevo.",
      },
      remove: {
        title: "Eliminar categoría",
        message: (name: string) => `¿Eliminar la categoría “${name}”?`,
        confirm: "Eliminar",
        cancel: "Cancelar",
        inUse:
          "No se puede eliminar: hay productos en esta categoría. Reasígnalos primero.",
        error: "No se pudo eliminar la categoría. Intenta de nuevo.",
      },
    },
    batches: {
      title: "Lotes",
      subtitle: "Inventario por lote (informativo). El stock del producto rige los pedidos.",
      empty: "Este producto no tiene lotes registrados.",
      lotNumber: "Número de lote",
      expiresAt: "Vencimiento",
      noExpiry: "Sin vencimiento",
      stock: "Unidades",
      add: "Agregar lote",
      adding: "Agregando…",
      addError: "No se pudo agregar el lote. Intenta de nuevo.",
      delete: "Eliminar lote",
      deleteError: "No se pudo eliminar el lote. Intenta de nuevo.",
    },
  },

  addresses: {
    title: "Mis direcciones",
    subtitle: "Administra tus direcciones de envío.",
    manage: "Mis direcciones",
    new: "Nueva dirección",
    edit: "Editar",
    empty: "Aún no tienes direcciones guardadas.",
    emptyHint: "Agrega una para agilizar tus envíos.",
    form: {
      newTitle: "Nueva dirección",
      editTitle: "Editar dirección",
      label: "Etiqueta",
      labelHint: "Opcional. Ej. Casa, Trabajo.",
      labelPlaceholder: "Casa, Trabajo…",
      address: "Dirección",
      addressPlaceholder: "Calle, edificio, apartamento…",
      city: "Ciudad",
      state: "Estado",
      zipCode: "Código postal",
      zipOptional: "Opcional",
      save: "Guardar",
      saving: "Guardando…",
      cancel: "Cancelar",
      saveError: "No se pudo guardar la dirección. Intenta de nuevo.",
      notIdentified: "Debes identificarte para administrar direcciones.",
    },
    remove: {
      title: "Eliminar dirección",
      message: (label: string) =>
        `¿Eliminar “${label}”? Esta acción no se puede deshacer.`,
      confirm: "Eliminar",
      cancel: "Cancelar",
      error: "No se pudo eliminar la dirección. Intenta de nuevo.",
    },
  },

  nav: {
    catalog: "Catálogo",
    cart: "Carrito",
    addresses: "Direcciones",
    operator: "Operador",
    orders: "Órdenes",
    products: "Productos",
    categories: "Categorías",
  },
} as const;
